<a href="https://colab.research.google.com/github/Tasyasyaaaaa/PembelajaranMesin/blob/main/World_University_Rankings_dataset_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**TUGAS MACHINE LEARNING A**

    Nama : Tasya
    NIM  : H081221043
    Prodi: Ilmu Aktuaria

In [2]:
import pandas as pd

In [3]:
dataset = '/content/timesData.csv'

In [4]:
data = pd.read_csv(dataset)

In [5]:
data

,world_rank,university_name,country,teaching,international,research,citations,income,total_score,num_students,student_staff_ratio,international_students,female_male_ratio,year
0,1,Harvard University,United States of America,99.7,72.4,98.7,98.8,34.5,96.1,"20,152",8.9,25%,NaN,2011
1,2,California Institute of Technology,United States of America,97.7,54.6,98.0,99.9,83.7,96.0,"2,243",6.9,27%,33 : 67,2011
2,3,Massachusetts Institute of Technology,United States of America,97.8,82.3,91.4,99.9,87.5,95.6,"11,074",9.0,33%,37 : 63,2011
3,4,Stanford University,United States of America,98.3,29.5,98.1,99.2,64.3,94.3,"15,596",7.8,22%,42 : 58,2011
4,5,Princeton University,United States of America,90.9,70.3,95.4,99.9,-,94.2,"7,929",8.4,27%,45 : 55,2011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2598,601-800,Yeungnam University,South Korea,18.6,24.3,10.9,26.5,35.4,-,"21,958",15.3,3%,48 : 52,2016
2599,601-800,Yıldız Technical University,Turkey,14.5,14.9,7.6,19.3,44.0,-,"31,268",28.7,2%,36 : 64,2016
2600,601-800,Yokohama City University,Japan,24.0,16.1,10.2,36.4,37.9,-,"4,122",3.7,3%,NaN,2016
2601,601-800,Yokohama National University,Japan,20.1,23.3,16.0,13.5,40.4,-,"10,117",12.1,8%,28 : 72,2016
2602,601-800,Yuan Ze University,Taiwan,16.2,17.7,18.3,28.6,39.8,-,"8,663",20.6,4%,43 : 57,2016

In [6]:
data.head()

,world_rank,university_name,country,teaching,international,research,citations,income,total_score,num_students,student_staff_ratio,international_students,female_male_ratio,year
0,1,Harvard University,United States of America,99.7,72.4,98.7,98.8,34.5,96.1,"20,152",8.9,25%,NaN,2011
1,2,California Institute of Technology,United States of America,97.7,54.6,98.0,99.9,83.7,96.0,"2,243",6.9,27%,33 : 67,2011
2,3,Massachusetts Institute of Technology,United States of America,97.8,82.3,91.4,99.9,87.5,95.6,"11,074",9.0,33%,37 : 63,2011
3,4,Stanford University,United States of America,98.3,29.5,98.1,99.2,64.3,94.3,"15,596",7.8,22%,42 : 58,2011
4,5,Princeton University,United States of America,90.9,70.3,95.4,99.9,-,94.2,"7,929",8.4,27%,45 : 55,2011

In [7]:
print(data.dtypes)

world_rank                 object
university_name            object
country                    object
teaching                  float64
international              object
research                  float64
citations                 float64
income                     object
total_score                object
num_students               object
student_staff_ratio       float64
international_students     object
female_male_ratio          object
year                        int64
dtype: object

In [8]:
datanoid = data.drop(data.columns[4],axis=1)

In [10]:
datanoid

,world_rank,university_name,country,teaching,research,citations,income,total_score,num_students,student_staff_ratio,international_students,female_male_ratio,year
0,1,Harvard University,United States of America,99.7,98.7,98.8,34.5,96.1,"20,152",8.9,25%,NaN,2011
1,2,California Institute of Technology,United States of America,97.7,98.0,99.9,83.7,96.0,"2,243",6.9,27%,33 : 67,2011
2,3,Massachusetts Institute of Technology,United States of America,97.8,91.4,99.9,87.5,95.6,"11,074",9.0,33%,37 : 63,2011
3,4,Stanford University,United States of America,98.3,98.1,99.2,64.3,94.3,"15,596",7.8,22%,42 : 58,2011
4,5,Princeton University,United States of America,90.9,95.4,99.9,-,94.2,"7,929",8.4,27%,45 : 55,2011
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2598,601-800,Yeungnam University,South Korea,18.6,10.9,26.5,35.4,-,"21,958",15.3,3%,48 : 52,2016
2599,601-800,Yıldız Technical University,Turkey,14.5,7.6,19.3,44.0,-,"31,268",28.7,2%,36 : 64,2016
2600,601-800,Yokohama City University,Japan,24.0,10.2,36.4,37.9,-,"4,122",3.7,3%,NaN,2016
2601,601-800,Yokohama National University,Japan,20.1,16.0,13.5,40.4,-,"10,117",12.1,8%,28 : 72,2016
2602,601-800,Yuan Ze University,Taiwan,16.2,18.3,28.6,39.8,-,"8,663",20.6,4%,43 : 57,2016

In [11]:
data.describe()

          teaching     research    citations  student_staff_ratio         year
count  2603.000000  2603.000000  2603.000000          2544.000000  2603.000000
mean     37.801498    35.910257    60.921629            18.445283  2014.075682
std      17.604218    21.254805    23.073219            11.458698     1.685733
min       9.900000     2.900000     1.200000             0.600000  2011.000000
25%      24.700000    19.600000    45.500000            11.975000  2013.000000
50%      33.900000    30.500000    62.500000            16.100000  2014.000000
75%      46.400000    47.250000    79.050000            21.500000  2016.000000
max      99.700000    99.400000   100.000000           162.600000  2016.000000

In [13]:
data.loc[:,"teaching":].corr()

<ipython-input-13-93f86c6131d2>:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  data.loc[:,"teaching":].corr()

,teaching,research,citations,student_staff_ratio,year
teaching,1.000000,0.913120,0.503867,-0.282630,-0.278108
research,0.913120,1.000000,0.525264,-0.198841,-0.274451
citations,0.503867,0.525264,1.000000,-0.137737,-0.173544
student_staff_ratio,-0.282630,-0.198841,-0.137737,1.000000,0.060728
year,-0.278108,-0.274451,-0.173544,0.060728,1.000000

**Dengan API**

In [14]:
!pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.10/dist-packages (1.5.16)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.10/dist-packages (from kaggle) (1.16.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from kaggle) (2024.2.2)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.10/dist-packages (from kaggle) (2.8.2)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from kaggle) (2.31.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from kaggle) (4.66.2)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.10/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.10/dist-packages (from kaggle) (2.0.7)
Requirement already satisfied: bleach in /usr/local/lib/python3.10/dist-packages (from kaggle) (6.1.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.10/dist-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.10/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->kaggle) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->kaggle) (3.6)

In [15]:
import os
from google.colab import files

# Pastikan file kaggle.json sudah diunggah
if not os.path.exists("/root/.kaggle/kaggle.json"):
    uploaded = files.upload()
    for fn in uploaded.keys():
        print('User uploaded file "{name}" with length {length} bytes'.format(
            name=fn, length=len(uploaded[fn])))
    # Pindahkan file kaggle.json ke direktori yang tepat
    !mkdir -p ~/.kaggle
    !mv kaggle.json ~/.kaggle/
    !chmod 600 /root/.kaggle/kaggle.json

Saving kaggle.json to kaggle (1).json
User uploaded file "kaggle (1).json" with length 64 bytes

In [16]:
!kaggle datasets list -s "rank university"

Warning: Looks like you're using an outdated API Version, please consider updating (server 1.6.7 / client 1.5.16)
ref                                                      title                                      size  lastUpdated          downloadCount  voteCount  usabilityRating
-------------------------------------------------------  ----------------------------------------  -----  -------------------  -------------  ---------  ---------------
mylesoneill/world-university-rankings                    World University Rankings                   1MB  2019-11-13 18:48:56          85401       1064  0.7941176
alitaqi000/world-university-rankings-2023                World University Rankings 2023             70KB  2023-08-31 14:35:38           5533         79  1.0
r1chardson/the-world-university-rankings-2011-2023       THE World University Rankings 2011-2024     2MB  2024-02-27 08:09:56           6162         97  1.0
jkanthony/world-university-rankings-202223               World University Rankings 2023             57KB  2022-06-11 05:26:30           4923         61  0.9411765
whenamancodes/world-university-ranking-2022-2023         WORLD UNIVERSITY RANKING 2022 - 2023       39KB  2022-09-30 17:13:32           3111         45  1.0
joebeachcapital/qs-world-university-rankings-2024        QS World University Rankings 2024          70KB  2023-07-31 23:43:27           1309         43  1.0
joyshil0599/global-university-rankings-dataset-2023      Global University Rankings Dataset 2023    50KB  2023-07-30 21:30:46           1218         32  1.0
samiatisha/world-university-rankings-2023-clean-dataset  World University Rankings 2023 - Cleaned  237KB  2023-09-10 15:22:54           4136         56  1.0
padhmam/qs-world-university-rankings-2017-2022           QS World University Rankings 2017 - 2022  316KB  2022-02-06 13:35:59           5390         70  1.0
tariqbashir/world-university-ranking-2023                World University Ranking 2023              52KB  2023-03-26 15:48:58           1675         66  1.0
ddosad/timesworlduniversityrankings2024                  Times World University Rankings 2024      277KB  2023-09-29 11:36:45           1770         76  1.0
erfansobhaei/ultimate-university-ranking                 Ultimate University Ranking                 6MB  2023-05-06 21:17:19           1717         44  1.0
rafsunahmad/world-all-university-ranking-factors         World All University Ranking Factors       23KB  2023-12-20 15:05:51            787         27  1.0
divyansh22/qs-world-university-rankings                  QS World University Rankings              101KB  2020-06-12 11:40:03           2719         36  1.0
joebeachcapital/university-and-college-rankings-us-news  US University & College Rankings          100KB  2023-08-10 22:50:24            922         34  1.0
neellad3110/shanghai-world-university-rankings-2023      Shanghai World University Rankings 2023   627KB  2023-11-03 09:12:25            689         27  1.0
raymondtoo/the-world-university-rankings-2016-2024       THE World University Rankings 2016-2024   458KB  2024-01-12 10:27:35           1627         30  0.9411765
ahmadrafiee/university-world-ranking                     University world ranking (2108_2019)       25KB  2023-11-26 06:48:02             76         59  0.64705884
prasertk/qs-world-university-rankings-2021               QS World University Rankings 2017-2022    499KB  2021-12-25 09:21:11           1609         31  0.9117647
zohrehtofighizavareh/2023-qs-world-university-rankings   2023 QS World University Rankings          57KB  2022-09-17 17:04:31            570         79  0.7058824

In [17]:
!kaggle datasets download mylesoneill/world-university-rankings

Downloading world-university-rankings.zip to /content
 71% 1.00M/1.41M [00:00<00:00, 1.99MB/s]
100% 1.41M/1.41M [00:00<00:00, 2.61MB/s]

In [18]:
!unzip /content/world-university-rankings.zip

Archive:  /content/world-university-rankings.zip
  inflating: cwurData.csv
  inflating: education_expenditure_supplementary_data.csv
  inflating: educational_attainment_supplementary_data.csv
  inflating: school_and_country_table.csv
  inflating: shanghaiData.csv
replace timesData.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename:

,world_rank,institution,country,national_rank,quality_of_education,alumni_employment,quality_of_faculty,publications,influence,citations,broad_impact,patents,score,year
0,1,Harvard University,USA,1,7,9,1,1,1,1,NaN,5,100.00,2012
1,2,Massachusetts Institute of Technology,USA,2,9,17,3,12,4,4,NaN,1,91.67,2012
2,3,Stanford University,USA,3,17,11,5,4,2,2,NaN,15,89.50,2012
3,4,University of Cambridge,United Kingdom,1,10,24,4,16,16,11,NaN,50,86.17,2012
4,5,California Institute of Technology,USA,4,2,29,7,37,22,22,NaN,18,85.21,2012
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2195,996,University of the Algarve,Portugal,7,367,567,218,926,845,812,969.0,816,44.03,2015
2196,997,Alexandria University,Egypt,4,236,566,218,997,908,645,981.0,871,44.03,2015
2197,998,Federal University of Ceará,Brazil,18,367,549,218,830,823,812,975.0,824,44.03,2015
2198,999,University of A Coruña,Spain,40,367,567,218,886,974,812,975.0,651,44.02,2015
2199,1000,China Pharmaceutical University,China,83,367,567,218,861,991,812,981.0,547,44.02,2015